var date = new Date();
console.log(date);
var year = date.getFullYear();
console.log(year);
var currentDate = date.getDate();
console.log(currentDate);
var month = date.getMonth();
console.log(month);
var day = date.getDay();
console.log(day);
var hours = date.getHours();
console.log(hours);
var minutes = date.getMinutes();
console.log(minutes);
var seconds = date.getSeconds();
console.log(seconds);